import type { SectionConfig } from "./types";

// ── Status/label maps ──────────────────────────────────────────────────────────

export const CARD_TYPE_LABELS: Record<string, string> = {
  debito: "Débito",
  credito: "Crédito",
};

export const CARD_TYPE_COLORS: Record<string, string> = {
  debito: "default",
  credito: "accent",
};

export const SALE_STATUS_LABELS: Record<string, string> = {
  pendiente: "Pendiente",
  pagado: "Pagado",
  rechazado: "Rechazado",
};

export const SALE_STATUS_COLORS: Record<string, string> = {
  pendiente: "warning",
  pagado: "success",
  rechazado: "danger",
};

export const EXPENSE_CATEGORY_LABELS: Record<string, string> = {
  sueldos: "Sueldos equipo",
  retiros_socias: "Retiros de Socias",
  admin: "Servicios Admin.",
  iva_retenciones: "IVA y retenciones",
  docencia: "Servicios Docencia",
  banco: "Banco",
  plataformas: "Plataformas",
  publicidad: "Publicidad",
  caja_chica: "Caja Chica",
  otros: "Otros gastos",
};

export const EXPENSE_CATEGORY_COLORS: Record<string, string> = {
  sueldos: "success",
  retiros_socias: "danger",
  admin: "default",
  iva_retenciones: "warning",
  docencia: "accent",
  banco: "default",
  plataformas: "default",
  publicidad: "warning",
  caja_chica: "default",
  otros: "default",
};

export const PAYMENT_METHOD_LABELS: Record<string, string> = {
  transferencia: "Transferencia",
  transbank: "Transbank",
  efectivo: "Efectivo",
  otro: "Otro",
};

export const PAYMENT_METHOD_COLORS: Record<string, string> = {
  transferencia: "success",
  transbank: "accent",
  efectivo: "default",
  otro: "default",
};

export const PAYMENT_STATUS_LABELS: Record<string, string> = {
  pagado: "Pagado",
  pendiente: "Pendiente",
  vencido: "Vencido",
  parcial: "Parcial",
};

export const PAYMENT_STATUS_COLORS: Record<string, string> = {
  pagado: "success",
  pendiente: "warning",
  vencido: "danger",
  parcial: "default",
};

// ── Section configs ────────────────────────────────────────────────────────────

export const SECTIONS: SectionConfig[] = [
  {
    slug: "libro-diario",
    label: "Libro Diario",
    icon: "material-symbols:menu-book-outline",
    table: "acc_journal",
    defaultOrder: "fecha",
    columns: [
      {
        key: "fecha",
        label: "Fecha",
        type: "date",
        sortable: true,
        formField: { type: "date", required: true },
      },
      {
        key: "descripcion",
        label: "Descripción",
        type: "text",
        sortable: true,
        formField: { type: "text", placeholder: "Descripción del movimiento", required: true },
      },
      {
        key: "n_doc",
        label: "N° Doc",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "text", placeholder: "N° de documento" },
      },
      {
        key: "cargos",
        label: "Cargos",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "abonos",
        label: "Abonos",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "saldo",
        label: "Saldo",
        type: "currency",
        sortable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
    ],
    emptyForm: { fecha: "", descripcion: "", n_doc: "", cargos: 0, abonos: 0, saldo: 0 },
  },
  {
    slug: "historico",
    label: "Histórico",
    icon: "material-symbols:history",
    table: "acc_history",
    defaultOrder: "fecha",
    columns: [
      {
        key: "fecha",
        label: "Fecha",
        type: "date",
        sortable: true,
        formField: { type: "date", required: true },
      },
      {
        key: "descripcion",
        label: "Descripción",
        type: "text",
        sortable: true,
        formField: { type: "text", placeholder: "Descripción del movimiento", required: true },
      },
      {
        key: "n_doc",
        label: "N° Doc",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "text", placeholder: "N° de documento" },
      },
      {
        key: "cargos",
        label: "Cargos",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "abonos",
        label: "Abonos",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "saldo",
        label: "Saldo",
        type: "currency",
        sortable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "sucursal",
        label: "Sucursal",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "text", placeholder: "Sucursal", required: true },
      },
    ],
    emptyForm: { fecha: "", descripcion: "", n_doc: "", cargos: 0, abonos: 0, saldo: 0, sucursal: "" },
  },
  {
    slug: "transbank",
    label: "Transbank",
    icon: "material-symbols:credit-card-outline",
    table: "acc_card_sales",
    defaultOrder: "fecha_venta",
    columns: [
      {
        key: "fecha_venta",
        label: "Fecha Venta",
        type: "date",
        sortable: true,
        formField: { type: "date", required: true },
      },
      {
        key: "local",
        label: "Local",
        type: "text",
        formField: { type: "text", placeholder: "Local", required: true },
      },
      {
        key: "tipo_tarjeta",
        label: "Tipo",
        type: "status",
        colorMap: CARD_TYPE_COLORS,
        labelMap: CARD_TYPE_LABELS,
        formField: {
          type: "select",
          required: true,
          options: [
            { value: "debito", label: "Débito" },
            { value: "credito", label: "Crédito" },
          ],
        },
      },
      {
        key: "monto_bruto",
        label: "Monto Bruto",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "comision",
        label: "Comisión",
        type: "currency",
        summable: true,
        hiddenOnMobile: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "monto_neto",
        label: "Monto Neto",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "cuotas",
        label: "Cuotas",
        type: "number",
        hiddenOnMobile: true,
        formField: { type: "number", placeholder: "1" },
      },
      {
        key: "fecha_pago",
        label: "Fecha Pago",
        type: "date",
        hiddenOnMobile: true,
        formField: { type: "date" },
      },
      {
        key: "estado",
        label: "Estado",
        type: "status",
        colorMap: SALE_STATUS_COLORS,
        labelMap: SALE_STATUS_LABELS,
        formField: {
          type: "select",
          required: true,
          options: [
            { value: "pendiente", label: "Pendiente" },
            { value: "pagado", label: "Pagado" },
            { value: "rechazado", label: "Rechazado" },
          ],
        },
      },
    ],
    emptyForm: {
      fecha_venta: "",
      local: "",
      tipo_tarjeta: "debito",
      monto_bruto: 0,
      comision: 0,
      monto_neto: 0,
      cuotas: 1,
      fecha_pago: "",
      estado: "pendiente",
    },
  },
  {
    slug: "gastos",
    label: "Gastos",
    icon: "material-symbols:receipt-long-outline",
    table: "acc_expenses",
    defaultOrder: "fecha",
    columns: [
      {
        key: "fecha",
        label: "Fecha",
        type: "date",
        sortable: true,
        formField: { type: "date", required: true },
      },
      {
        key: "descripcion",
        label: "Descripción",
        type: "text",
        sortable: true,
        formField: { type: "text", placeholder: "Descripción del gasto", required: true },
      },
      {
        key: "categoria",
        label: "Categoría",
        type: "status",
        colorMap: EXPENSE_CATEGORY_COLORS,
        labelMap: EXPENSE_CATEGORY_LABELS,
        formField: {
          type: "select",
          required: true,
          options: [
            { value: "admin", label: "Servicios Admin" },
            { value: "docencia", label: "Docencia" },
            { value: "plataformas", label: "Plataformas" },
            { value: "publicidad", label: "Publicidad" },
            { value: "retiros_socias", label: "Retiros de Socias" },
          ],
        },
      },
      {
        key: "subcategoria",
        label: "Subcategoría",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "text", placeholder: "Subcategoría" },
      },
      {
        key: "monto",
        label: "Monto",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "proveedor",
        label: "Proveedor",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "text", placeholder: "Proveedor" },
      },
      {
        key: "n_doc",
        label: "N° Doc",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "text", placeholder: "N° de documento" },
      },
      {
        key: "notas",
        label: "Notas",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "textarea", placeholder: "Notas adicionales" },
      },
    ],
    emptyForm: {
      fecha: "",
      descripcion: "",
      categoria: "admin",
      subcategoria: "",
      monto: 0,
      proveedor: "",
      n_doc: "",
      notas: "",
    },
  },
  {
    slug: "escuela-v25",
    label: "Escuela v25",
    icon: "material-symbols:school-outline",
    table: "acc_program_payments",
    defaultOrder: "fecha_pago",
    programFilter: "escuela_v25",
    columns: [
      {
        key: "alumna_nombre",
        label: "Alumna",
        type: "text",
        sortable: true,
        formField: { type: "text", placeholder: "Nombre de la alumna", required: true },
      },
      {
        key: "concepto",
        label: "Concepto",
        type: "text",
        formField: { type: "text", placeholder: "Concepto del pago", required: true },
      },
      {
        key: "monto",
        label: "Monto",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "fecha_pago",
        label: "Fecha Pago",
        type: "date",
        sortable: true,
        formField: { type: "date" },
      },
      {
        key: "metodo_pago",
        label: "Método",
        type: "status",
        colorMap: PAYMENT_METHOD_COLORS,
        labelMap: PAYMENT_METHOD_LABELS,
        formField: {
          type: "select",
          required: true,
          options: [
            { value: "transferencia", label: "Transferencia" },
            { value: "transbank", label: "Transbank" },
            { value: "efectivo", label: "Efectivo" },
            { value: "otro", label: "Otro" },
          ],
        },
      },
      {
        key: "estado",
        label: "Estado",
        type: "status",
        colorMap: PAYMENT_STATUS_COLORS,
        labelMap: PAYMENT_STATUS_LABELS,
        formField: {
          type: "select",
          required: true,
          options: [
            { value: "pagado", label: "Pagado" },
            { value: "pendiente", label: "Pendiente" },
            { value: "vencido", label: "Vencido" },
            { value: "parcial", label: "Parcial" },
          ],
        },
      },
      {
        key: "mes",
        label: "Mes",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "text", placeholder: "Ej: Marzo 2026" },
      },
      {
        key: "notas",
        label: "Notas",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "textarea", placeholder: "Notas adicionales" },
      },
    ],
    emptyForm: {
      alumna_nombre: "",
      alumna_email: "",
      concepto: "",
      monto: 0,
      fecha_pago: "",
      metodo_pago: "transferencia",
      estado: "pendiente",
      mes: "",
      notas: "",
    },
  },
  {
    slug: "escuela-v26",
    label: "Escuela v26",
    icon: "material-symbols:school",
    table: "acc_program_payments",
    defaultOrder: "fecha_pago",
    programFilter: "escuela_v26",
    columns: [
      {
        key: "alumna_nombre",
        label: "Alumna",
        type: "text",
        sortable: true,
        formField: { type: "text", placeholder: "Nombre de la alumna", required: true },
      },
      {
        key: "concepto",
        label: "Concepto",
        type: "text",
        formField: { type: "text", placeholder: "Concepto del pago", required: true },
      },
      {
        key: "monto",
        label: "Monto",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "fecha_pago",
        label: "Fecha Pago",
        type: "date",
        sortable: true,
        formField: { type: "date" },
      },
      {
        key: "metodo_pago",
        label: "Método",
        type: "status",
        colorMap: PAYMENT_METHOD_COLORS,
        labelMap: PAYMENT_METHOD_LABELS,
        formField: {
          type: "select",
          required: true,
          options: [
            { value: "transferencia", label: "Transferencia" },
            { value: "transbank", label: "Transbank" },
            { value: "efectivo", label: "Efectivo" },
            { value: "otro", label: "Otro" },
          ],
        },
      },
      {
        key: "estado",
        label: "Estado",
        type: "status",
        colorMap: PAYMENT_STATUS_COLORS,
        labelMap: PAYMENT_STATUS_LABELS,
        formField: {
          type: "select",
          required: true,
          options: [
            { value: "pagado", label: "Pagado" },
            { value: "pendiente", label: "Pendiente" },
            { value: "vencido", label: "Vencido" },
            { value: "parcial", label: "Parcial" },
          ],
        },
      },
      {
        key: "mes",
        label: "Mes",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "text", placeholder: "Ej: Marzo 2026" },
      },
      {
        key: "notas",
        label: "Notas",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "textarea", placeholder: "Notas adicionales" },
      },
    ],
    emptyForm: {
      alumna_nombre: "",
      alumna_email: "",
      concepto: "",
      monto: 0,
      fecha_pago: "",
      metodo_pago: "transferencia",
      estado: "pendiente",
      mes: "",
      notas: "",
    },
  },
  {
    slug: "formacion-continua",
    label: "F. Continua",
    icon: "material-symbols:cast-for-education-outline",
    table: "acc_program_payments",
    defaultOrder: "fecha_pago",
    programFilter: "formacion_continua",
    columns: [
      {
        key: "alumna_nombre",
        label: "Participante",
        type: "text",
        sortable: true,
        formField: { type: "text", placeholder: "Nombre del participante", required: true },
      },
      {
        key: "concepto",
        label: "Concepto",
        type: "text",
        formField: { type: "text", placeholder: "Concepto del pago", required: true },
      },
      {
        key: "monto",
        label: "Monto",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "fecha_pago",
        label: "Fecha Pago",
        type: "date",
        sortable: true,
        formField: { type: "date" },
      },
      {
        key: "metodo_pago",
        label: "Método",
        type: "status",
        colorMap: PAYMENT_METHOD_COLORS,
        labelMap: PAYMENT_METHOD_LABELS,
        formField: {
          type: "select",
          required: true,
          options: [
            { value: "transferencia", label: "Transferencia" },
            { value: "transbank", label: "Transbank" },
            { value: "efectivo", label: "Efectivo" },
            { value: "otro", label: "Otro" },
          ],
        },
      },
      {
        key: "estado",
        label: "Estado",
        type: "status",
        colorMap: PAYMENT_STATUS_COLORS,
        labelMap: PAYMENT_STATUS_LABELS,
        formField: {
          type: "select",
          required: true,
          options: [
            { value: "pagado", label: "Pagado" },
            { value: "pendiente", label: "Pendiente" },
            { value: "vencido", label: "Vencido" },
            { value: "parcial", label: "Parcial" },
          ],
        },
      },
      {
        key: "mes",
        label: "Mes",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "text", placeholder: "Ej: Marzo 2026" },
      },
      {
        key: "notas",
        label: "Notas",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "textarea", placeholder: "Notas adicionales" },
      },
    ],
    emptyForm: {
      alumna_nombre: "",
      alumna_email: "",
      concepto: "",
      monto: 0,
      fecha_pago: "",
      metodo_pago: "transferencia",
      estado: "pendiente",
      mes: "",
      notas: "",
    },
  },
  {
    slug: "consolidado",
    label: "Consolidado",
    icon: "material-symbols:bar-chart-outline",
    table: "acc_monthly_summary",
    defaultOrder: "anio",
    columns: [
      {
        key: "anio",
        label: "Año",
        type: "number",
        sortable: true,
        formField: { type: "number", placeholder: "2026", required: true },
      },
      {
        key: "mes",
        label: "Mes",
        type: "number",
        sortable: true,
        formField: { type: "number", placeholder: "1-12", required: true },
      },
      {
        key: "categoria",
        label: "Categoría",
        type: "text",
        sortable: true,
        formField: { type: "text", placeholder: "Categoría", required: true },
      },
      {
        key: "total_ingresos",
        label: "Ingresos",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "total_gastos",
        label: "Gastos",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "resultado",
        label: "Resultado",
        type: "currency",
        sortable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "notas",
        label: "Notas",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "textarea", placeholder: "Notas adicionales" },
      },
    ],
    emptyForm: { anio: 2026, mes: 1, categoria: "", total_ingresos: 0, total_gastos: 0, resultado: 0, notas: "" },
  },
  {
    slug: "proyeccion",
    label: "Proyección",
    icon: "material-symbols:trending-up-outline",
    table: "acc_budget",
    defaultOrder: "anio",
    columns: [
      {
        key: "anio",
        label: "Año",
        type: "number",
        sortable: true,
        formField: { type: "number", placeholder: "2026", required: true },
      },
      {
        key: "mes",
        label: "Mes",
        type: "number",
        sortable: true,
        formField: { type: "number", placeholder: "1-12", required: true },
      },
      {
        key: "categoria",
        label: "Categoría",
        type: "text",
        sortable: true,
        formField: { type: "text", placeholder: "Categoría", required: true },
      },
      {
        key: "monto_estimado",
        label: "Estimado",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0", required: true },
      },
      {
        key: "monto_real",
        label: "Real",
        type: "currency",
        sortable: true,
        summable: true,
        formField: { type: "number", placeholder: "0" },
      },
      {
        key: "variacion",
        label: "Variación",
        type: "currency",
        // No formField — computed by DB
      },
      {
        key: "notas",
        label: "Notas",
        type: "text",
        hiddenOnMobile: true,
        formField: { type: "textarea", placeholder: "Notas adicionales" },
      },
    ],
    emptyForm: { anio: 2026, mes: 1, categoria: "", monto_estimado: 0, monto_real: 0, notas: "" },
  },
];
